apiVersion: skaffold/v2beta4
kind: Config
build:
  artifacts:
  - image: docker.pkg.github.com/tcd1980/ticketing/auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: docker.pkg.github.com/tcd1980/ticketing/client
    context: client
    sync:
      manual:
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile-dev
  - image: docker.pkg.github.com/tcd1980/ticketing/tickets
    context: tickets
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: docker.pkg.github.com/tcd1980/ticketing/orders
    context: orders
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: docker.pkg.github.com/tcd1980/ticketing/expiration
    context: expiration
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: docker.pkg.github.com/tcd1980/ticketing/payments
    context: payments
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: docker.pkg.github.com/tcd1980/ticketing/api
    context: api
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: docker.pkg.github.com/tcd1980/ticketing/notifications
    context: notifications
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubeContext: docker-desktop
  kubectl:
    manifests:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
