apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
  - image: shopramsydev/api
    context: api
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/auth
    context: auth
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/categories
    context: categories
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/client
    context: client
    sync:
      manual:
      - src: '**/*.ts*'
        dest: .
      - src: '**/*.css*'
        dest: .
    docker:
      dockerfile: Dockerfile-dev
  - image: shopramsydev/expiration
    context: expiration
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/logs
    context: logs
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/media
    context: media
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/notifications
    context: notifications
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/orders
    context: orders
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/payments
    context: payments
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
  - image: shopramsydev/products
    context: products
    sync:
      manual:
      - src: src/**/*.ts
        dest: .
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/development/*
