export enum Subjects {
  ProductCreated = 'product:created',
  ProductUpdated = 'product:updated',
  ProductDeleted = 'product:deleted',
  CategoryCreated = 'category:created',
  CategoryUpdated = 'category:updated',
  CategoryDeleted = 'category:deleted',
  OrderCreated = 'order:created',
  OrderCancelled = 'order:cancelled',
  ExpirationComplete = 'expiration:complete',
  PaymentCreated = 'payment:created',
  UserSignedUp = 'user:signed-up',
  UserForgotPassword = 'user:forgot-password',
  UserVerifyPhoneNumber = 'user:verify-phone-number',
}