apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  containers:
    - name: api
      image: docker.pkg.github.com/tcd1980/ticketing/api
      env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_KEY
  imagePullSecrets:
    - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: api-srv
spec:
  selector:
    app: api
  ports:
    - name: api
      protocol: TCP
      port: 80
      targetPort: 80
