apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-depl
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: logs
          image: shopramsydev/media
          ports:
          - name: server-port
            containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: server-port
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: server-port
            failureThreshold: 30
            periodSeconds: 10  
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get pod name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shop
            - name: MONGO_URI
              value: 'mongodb://media-mongo-srv:27017/media'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-key
                  key: SPACES_KEY
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_SECRET
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: media-srv
  namespace: production
spec:
  selector:
    app: media
  ports:
    - name: media
      protocol: TCP
      port: 3000
      targetPort: 3000
