apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-depl
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: shopramsydev/cart
          resources: {}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
              httpHeaders:
              - name: X-Custom-Header
                value: LivenessProbe
            failureThreshold: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
              httpHeaders:
              - name: X-Custom-Header
                value: ReadinessProbe
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
              httpHeaders:
              - name: X-Custom-Header
                value: StartupProbe
            failureThreshold: 30
            periodSeconds: 10     
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get pod name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shop
            - name: MONGO_URI
              value: 'mongodb://shop-mongodb-replicaset-0.shop-mongodb-replicaset,shop-mongodb-replicaset-1.shop-mongodb-replicaset,shop-mongodb-replicaset-2.shop-mongodb-replicaset:27017/cart'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: cart-srv
  namespace: development
spec:
  selector:
    app: cart
  ports:
    - name: cart
      protocol: TCP
      port: 3000
      targetPort: 3000
