apiVersion: apps/v1
kind: Deployment
metadata:
  name: categories-depl
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: categories
  template:
    metadata:
      labels:
        app: categories
    spec:
      containers:
        - name: categories
          image: shopramsydev/categories
          ports:
          - name: server-port
            containerPort: 3000
            hostPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: server-port
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /healthz
              port: liveness-port
            failureThreshold: 30
            periodSeconds: 10    
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get pod name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shop
            - name: MONGO_URI
              value: 'mongodb://categories-mongo-srv:27017/categories'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: categories-srv
  namespace: development
spec:
  selector:
    app: categories
  ports:
    - name: categories
      protocol: TCP
      port: 3000
      targetPort: 3000
