apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-depl
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: logs
          image: shopramsydev/logs
          resources: {}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get pod name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shop
            - name: MONGO_URI
              value: 'mongodb://shop-mongodb-replicaset-0.shop-mongodb-replicaset,shop-mongodb-replicaset-1.shop-mongodb-replicaset,shop-mongodb-replicaset-2.shop-mongodb-replicaset:27017/logs'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: logs-srv
  namespace: development
spec:
  selector:
    app: logs
  ports:
    - name: logs
      protocol: TCP
      port: 3000
      targetPort: 3000
