apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-depl
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media
  template:
    metadata:
      labels:
        app: media
    spec:
      containers:
        - name: logs
          image: shopramsydev/media
          resources: {}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Get pod name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: shop
            - name: MONGO_URI
              value: 'mongodb://shop-mongodb-replicaset-0.shop-mongodb-replicaset,shop-mongodb-replicaset-1.shop-mongodb-replicaset,shop-mongodb-replicaset-2.shop-mongodb-replicaset:27017/media'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: SPACES_KEY
              valueFrom:
                secretKeyRef:
                  name: spaces-key
                  key: SPACES_KEY
            - name: SPACES_SECRET
              valueFrom:
                secretKeyRef:
                  name: spaces-secret
                  key: SPACES_SECRET
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: media-srv
  namespace: development
spec:
  selector:
    app: media
  ports:
    - name: media
      protocol: TCP
      port: 3000
      targetPort: 3000
