apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-mongo-depl
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-mongo
  template:
    metadata:
      labels:
        app: products-mongo
    spec:
      containers:
        - name: products-mongo
          image: mongo
          resources: {}
          livenessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            exec:
              command:
              - mongo
              - --eval
              - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          env:
            - name: MONGO_DATA_DIR
              value: /data/db
            - name: MONGO_LOG_DIR
              value: /dev/null
          volumeMounts:
            - name: products-mongo-storage
              mountPath: /data/db
      terminationGracePeriodSeconds: 10
      volumes:
        - name: products-mongo-storage
          persistentVolumeClaim:
            claimName: products-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: products-mongo-srv
  namespace: development
spec:
  selector:
    app: products-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
