name: deploy-notifications

on:
  push:
    branches:
      - master
    paths:
      - 'notifications/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd notifications && docker build -t shopramsydev/notifications .
      - run: docker login docker.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push shopramsydev/notifications
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ramsy-dev
      - run: kubectl -n production rollout restart deployment notifications-depl
