name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cd auth && docker build -t docker.pkg.github.com/tcd1980/ticketing/auth .
      - run: docker push docker.pkg.github.com/tcd1980/ticketing/auth

