name: tests-media

on:
  pull_request:
    paths:
      - 'media/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd media && yarn install && yarn run test:ci
