name: tests-api

on:
  pull_request:
    paths:
      - 'api/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd api && yarn install && yarn run test:ci
