name: tests-client

on:
  pull_request:
    paths:
      - 'client/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd client && yarn install && yarn run test:ci
