name: tests-products

on:
  pull_request:
    paths:
      - 'products/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd products && yarn install && yarn run test:ci
